import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["selector", 'html[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        /* Theme-aware tokens (unified --ui-* design token contract) */
        theme: {
          bg: "var(--ui-surface-page)",
          "bg-elevated": "var(--ui-surface-raised)",
          text: "var(--ui-text-primary)",
          muted: "var(--ui-text-secondary)",
          surface: "var(--ui-surface-raised)",
          border: "var(--ui-stroke-soft)",
          "border-subtle": "var(--ui-stroke-subtle)",
          ring: "var(--ui-stroke-strong)",
          "input-bg": "var(--ui-surface-raised)",
          "input-text": "var(--ui-text-primary)",
          "input-placeholder": "var(--ui-text-placeholder)",
          "code-bg": "var(--ui-surface-code)",
          "code-text": "var(--ui-text-code)",
          overlay: "var(--ui-overlay-default)",
          "surface-muted": "var(--ui-surface-muted)",
          "graph-edge": "var(--ui-graph-edge)",
          "graph-edge-critical": "var(--ui-graph-edge-critical)",
          /* Semantic tokens (--ui-* design token contract) */
          error: "var(--ui-status-error-text)",
          "error-bg": "var(--ui-status-error-bg)",
          "error-text": "var(--ui-status-error-text)",
          "error-border": "var(--ui-status-error-border)",
          "error-solid": "var(--ui-status-error)",
          "error-solid-hover": "var(--ui-status-error-solid-hover)",
          "success-bg": "var(--ui-status-success-bg)",
          "success-text": "var(--ui-status-success-text)",
          "success-border": "var(--ui-status-success-border)",
          "success-solid": "var(--ui-status-success)",
          "success-muted": "var(--ui-status-success-muted)",
          "warning-bg": "var(--ui-status-warning-bg)",
          "warning-text": "var(--ui-status-warning-text)",
          "warning-border": "var(--ui-status-warning-border)",
          "warning-solid": "var(--ui-status-warning)",
          "info-bg": "var(--ui-accent-tint)",
          "info-text": "var(--ui-status-info-text)",
          "info-border": "var(--ui-status-info-border)",
          "info-solid": "var(--ui-accent-primary)",
          "notification-error": "var(--ui-notification-error)",
          "notification-warning": "var(--ui-notification-warning)",
          "notification-info": "var(--ui-notification-info)",
          "notification-success": "var(--ui-notification-success)",
          "feedback-bug-bg": "var(--ui-feedback-bug-bg)",
          "feedback-bug-text": "var(--ui-feedback-bug-text)",
          "feedback-feature-bg": "var(--ui-feedback-feature-bg)",
          "feedback-feature-text": "var(--ui-feedback-feature-text)",
          "feedback-ux-bg": "var(--ui-feedback-ux-bg)",
          "feedback-ux-text": "var(--ui-feedback-ux-text)",
          "feedback-scope-bg": "var(--ui-feedback-scope-bg)",
          "feedback-scope-text": "var(--ui-feedback-scope-text)",
          "status-backlog": "var(--ui-status-indicator-backlog)",
          "status-ready": "var(--ui-status-info)",
          "status-in-progress": "var(--ui-status-indicator-in-progress)",
          "status-in-review": "var(--ui-status-indicator-in-review)",
          "status-done": "var(--ui-status-success)",
          "status-blocked": "var(--ui-status-error)",
        },
        surface: {
          page: "var(--ui-surface-page)",
          raised: "var(--ui-surface-raised)",
          muted: "var(--ui-surface-muted)",
          code: "var(--ui-surface-code)",
        },
        stroke: {
          soft: "var(--ui-stroke-soft)",
          strong: "var(--ui-stroke-strong)",
          focus: "var(--ui-stroke-focus)",
        },
        accent: {
          primary: "var(--ui-accent-primary)",
          strong: "var(--ui-accent-strong)",
          tint: "var(--ui-accent-tint)",
        },
        status: {
          info: "var(--ui-status-info)",
          success: "var(--ui-status-success)",
          warning: "var(--ui-status-warning)",
          error: "var(--ui-status-error)",
        },
        brand: {
          50: "#edf5ff",
          100: "#d9eaff",
          200: "#bdd9ff",
          300: "#8abfff",
          400: "#5aa5ff",
          500: "#2f89f1",
          600: "#0071e3",
          700: "#005bb5",
          800: "#00488e",
          900: "#003c75",
          950: "#00264a",
        },
      },
      fontFamily: {
        sans: [
          "SF Pro Text",
          "SF Pro Display",
          "-apple-system",
          "BlinkMacSystemFont",
          "Inter",
          "Segoe UI",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        mono: ["JetBrains Mono", "Menlo", "monospace"],
      },
      keyframes: {
        "slide-up-fade": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-out-fade": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-8px)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "logo-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "slide-up-fade": "slide-up-fade 0.2s ease-out",
        "slide-out-fade": "slide-out-fade 0.2s ease-out forwards",
        "slide-in-right": "slide-in-right 0.2s ease-out",
        "slide-in-left": "slide-in-left 0.2s ease-out",
        "fade-in": "fade-in 0.15s ease-out",
        "logo-pulse": "logo-pulse 1.2s ease-in-out infinite",
        "logo-pulse-slow": "logo-pulse 3.6s ease-in-out infinite",
      },
    },
  },
  plugins: [typography],
};
